export const jobListings = [
  {
    title: "AI/ML Engineer",
    companyId: "680cf828941a6f1715fdc719",
    location: "London",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71a",
    location: "Mumbai",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "DevOps Engineer",
    companyId: "680cf828941a6f1715fdc71b",
    location: "California",
    level: "Senior Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Cloud Engineer",
    companyId: "680cf828941a6f1715fdc71c",
    location: "Bangalore",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71d",
    location: "New York",
    level: "Intermediate Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc719",
    location: "Austin",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 11 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "Data Analyst",
    companyId: "680cf828941a6f1715fdc71c",
    location: "London",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 2 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "Backend Developer",
    companyId: "680cf828941a6f1715fdc720",
    location: "Austin",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As a Backend Developer, you'll develop scalable server-side applications, manage APIs, and work closely with frontend and DevOps teams.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc71e",
    location: "Washington",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "AI/ML Engineer",
    companyId: "680cf828941a6f1715fdc71e",
    location: "Bangalore",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc71f",
    location: "New York",
    level: "Senior Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc720",
    location: "London",
    level: "Entry Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "AI/ML Engineer",
    companyId: "680cf828941a6f1715fdc71b",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Frontend Developer",
    companyId: "680cf828941a6f1715fdc721",
    location: "Mumbai",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 11 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Data Analyst",
    companyId: "680cf828941a6f1715fdc71f",
    location: "London",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc71d",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71b",
    location: "Bangalore",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "AI/ML Engineer",
    companyId: "680cf828941a6f1715fdc719",
    location: "Washington",
    level: "Entry Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc71b",
    location: "Toronto",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc71b",
    location: "California",
    level: "Senior Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "Data Analyst",
    companyId: "680cf828941a6f1715fdc722",
    location: "Chennai",
    level: "Entry Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "Frontend Developer",
    companyId: "680cf828941a6f1715fdc719",
    location: "Bangalore",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Software Tester",
    companyId: "680cf828941a6f1715fdc719",
    location: "California",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Product Manager",
    companyId: "680cf828941a6f1715fdc719",
    location: "Toronto",
    level: "Senior Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "management",
  },
  {
    title: "Frontend Developer",
    companyId: "680cf828941a6f1715fdc71d",
    location: "Austin",
    level: "Intermediate Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 10 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "AI/ML Engineer",
    companyId: "680cf828941a6f1715fdc719",
    location: "Mumbai",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Cloud Engineer",
    companyId: "680cf828941a6f1715fdc71a",
    location: "Austin",
    level: "Entry Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Cloud Engineer",
    companyId: "680cf828941a6f1715fdc71b",
    location: "Toronto",
    level: "Intermediate Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 8 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Software Tester",
    companyId: "680cf828941a6f1715fdc71e",
    location: "Washington",
    level: "Senior Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "AI/ML Engineer",
    companyId: "680cf828941a6f1715fdc71d",
    location: "California",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Backend Developer",
    companyId: "680cf828941a6f1715fdc71c",
    location: "New York",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "As a Backend Developer, you'll develop scalable server-side applications, manage APIs, and work closely with frontend and DevOps teams.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Data Analyst",
    companyId: "680cf828941a6f1715fdc721",
    location: "California",
    level: "Entry Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "Data Analyst",
    companyId: "680cf828941a6f1715fdc71c",
    location: "Toronto",
    level: "Senior Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "Cloud Engineer",
    companyId: "680cf828941a6f1715fdc720",
    location: "Chennai",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Software Tester",
    companyId: "680cf828941a6f1715fdc71f",
    location: "Washington",
    level: "Entry Level",
    ctc: "CTC: 110k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc720",
    location: "New York",
    level: "Entry Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "Data Analyst",
    companyId: "680cf828941a6f1715fdc722",
    location: "Hyderabad",
    level: "Senior Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 7 months ago",
    description:
      "As a Data Analyst, you will interpret complex data sets, provide actionable insights, and support data-driven decision-making.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71a",
    location: "London",
    level: "Intermediate Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 3 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "Security Analyst",
    companyId: "680cf828941a6f1715fdc719",
    location: "New York",
    level: "Senior Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 4 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "Backend Developer",
    companyId: "680cf828941a6f1715fdc71e",
    location: "Hyderabad",
    level: "Intermediate Level",
    ctc: "CTC: 85k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "As a Backend Developer, you'll develop scalable server-side applications, manage APIs, and work closely with frontend and DevOps teams.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71e",
    location: "California",
    level: "Entry Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 0 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71b",
    location: "Mumbai",
    level: "Senior Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71d",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 10 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "Security Analyst",
    companyId: "680cf828941a6f1715fdc71e",
    location: "Mumbai",
    level: "Intermediate Level",
    ctc: "CTC: 102k",
    apply_label: "Apply Now",
    posted: "Posted 1 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "dataScience",
  },
  {
    title: "Software Tester",
    companyId: "680cf828941a6f1715fdc71d",
    location: "Austin",
    level: "Intermediate Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 11 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc71e",
    location: "Bangalore",
    level: "Intermediate Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 5 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "DevOps Engineer",
    companyId: "680cf828941a6f1715fdc722",
    location: "Chennai",
    level: "Senior Level",
    ctc: "CTC: 95k",
    apply_label: "Apply Now",
    posted: "Posted 6 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "UX Designer",
    companyId: "680cf828941a6f1715fdc720",
    location: "Austin",
    level: "Entry Level",
    ctc: "CTC: 120k",
    apply_label: "Apply Now",
    posted: "Posted 9 months ago",
    description:
      "Be a part of our growing team and help build innovative solutions that make a difference.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "designing",
  },
  {
    title: "AI/ML Engineer",
    companyId: "680cf828941a6f1715fdc71a",
    location: "Chennai",
    level: "Intermediate Level",
    ctc: "CTC: 75k",
    apply_label: "Apply Now",
    posted: "Posted 12 months ago",
    description:
      "As an AI/ML Engineer, you'll innovate on intelligent systems, build learning algorithms, and apply ML models to real-world challenges.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
  {
    title: "Frontend Developer",
    companyId: "680cf828941a6f1715fdc719",
    location: "Bangalore",
    level: "Intermediate Level",
    ctc: "CTC: 130k",
    apply_label: "Apply Now",
    posted: "Posted 12 months ago",
    description:
      "As a Frontend Developer, you will design interactive interfaces, optimize performance, and bring creative ideas to life using modern web technologies.",
    responsibilities: [
      "Design and develop scalable solutions.",
      "Work with cross-functional teams to ensure quality.",
      "Optimize systems for performance and cost.",
      "Implement security best practices.",
      "Provide support and troubleshooting as needed.",
    ],
    skills: [
      "Strong programming skills.",
      "Experience with cloud platforms or full-stack development.",
      "Good understanding of DevOps and CI/CD.",
      "Knowledge of security and networking principles.",
      "Excellent communication and problem-solving skills.",
    ],
    category: "programming",
  },
];
